on:
    pull_request:
      types:
        - closed
      branches:
        - master

permissions:
    contents: write

jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - name: Checkout documentation
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: doc

      - name: Checkout history file
        uses: actions/checkout@v4
        with:
            repository: haszi/fileModHistoryRepo
            path: fileModHistory

      - name: Get update script
        run: wget https://raw.githubusercontent.com/haszi/testRepo/master/scripts/updateModHistory.php

      - name: Update fileModHistory.php
        run: |
          # Generate the updates to fileModHistory.php
          php updateModHistory.php --docs-path=doc/ --history-path=fileModHistory/fileModHistory-repo1.php
  
          # Configure git
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
  
          # Switch to the file mod history directory
          cd fileModHistory/

          # Add and amend generated changes to the last commit
          git add fileModHistory.php
          git commit -m "Update fileModHistory.php"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
