on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: Checkout documentation
          uses: actions/checkout@v4

        - name: Checkout fileModHistory files
          uses: actions/checkout@v4
          with:
            repository: haszi/fileModHistoryRepo
            token: ${{ secrets.PAT_TOKEN }}

        - name: Update fileModHistory.php
          env:
            GITHUB_TOKEN
          run: |
            # generate the updates to fileModHistory.php
            php updateModHistory.php
            
            # Configure git
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # add and amend generated changes to the last commit
            git add fileModHistory.php
            git commit -m "Update fileModHistory.php"
            
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.PAT_TOKEN }}
            repository: haszi/fileModHistoryRepo
            branch: master
            force: true